/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.eXXXtreme;

import org.eclipse.eXXXtreme.TutorialStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TutorialStandaloneSetup extends TutorialStandaloneSetupGenerated {
  public static void doSetup() {
    TutorialStandaloneSetup _tutorialStandaloneSetup = new TutorialStandaloneSetup();
    _tutorialStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
