/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.eXXXtreme;

import org.eclipse.eXXXtreme.AbstractTutorialRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TutorialRuntimeModule extends AbstractTutorialRuntimeModule {
}
