/**
 * generated by Xtext 2.9.0-SNAPSHOT
 */
package org.eclipse.eXXXtreme.ui;

import org.eclipse.eXXXtreme.ui.AbstractTutorialUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.xbase.ui.launching.JavaApplicationLaunchShortcut;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TutorialUiModule extends AbstractTutorialUiModule {
  public Class<? extends JavaApplicationLaunchShortcut> bindJavaApplicationLaunchShortcut() {
    return JavaApplicationLaunchShortcut.class;
  }
  
  public TutorialUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
