/*
 * generated by Xtext
 */
package org.eclipse.eXXXtreme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.common.types.xtext.ui.ITypesProposalProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TutorialUiModule extends org.eclipse.eXXXtreme.ui.AbstractTutorialUiModule {
	public TutorialUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	@Override
	public Class<? extends ITypesProposalProvider> bindITypesProposalProvider() {
		return super.bindITypesProposalProvider();
	}
}
