/*
 * generated by Xtext
 */
package org.eclipse.eXXXtreme.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.xbase.ui.launching.JavaApplicationLaunchShortcut;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TutorialUiModule extends org.eclipse.eXXXtreme.ui.AbstractTutorialUiModule {
	public TutorialUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends JavaApplicationLaunchShortcut> bindJavaApplicationLaunchShortcut(){
		return JavaApplicationLaunchShortcut.class;
	}

}
