/*
 * generated by Xtext
 */
package org.eclipse.eXXXtreme;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TutorialRuntimeModule extends org.eclipse.eXXXtreme.AbstractTutorialRuntimeModule {

}
